# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907f9391a1b0bd1dfc35f76fdf2eabd3b3cd23a46f2de5e5e5c34b827c9cee031cb6e3f882f2a6daf076015d915bb77beb8d5fbd8c0ca985ce8cf43d25c4138c

test:
  secret_key_base: 05fc4aca53b6d2a8ede0f60c153afdfb6a13a9042e9de1abf5b4023744537f5b31a793abb968042575cf6b4566d0288e2061df89148627b90c2e390c512f9b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
